### ISSUE TITLE
FI: St1

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#100]
* __Brand__ : St1                            
* __Category__ : fuel                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/St1             
* __Opening hours__ : https://www.st1.fi/asemahaku                    
* __Source__ : https://www.st1.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
