### ISSUE TITLE
FI: Alko

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#101]
* __Brand__ : Alko                            
* __Category__ : alcohol                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Alko             
* __Opening hours__ : https://www.alko.fi/myymalat-palvelut                    
* __Source__ : https://www.alko.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
