### ISSUE TITLE
FI: Prisma

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#102]
* __Brand__ : Prisma                             
* __Category__ : Supermarket                     
* __Opening rule__ : shops open as usual                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Prisma_(kauppaketju)             
* __Opening hours__ : https://www.foodie.fi/store                    
* __Source__ : https://www.foodie.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
