### ISSUE TITLE
FI: Hesburger

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#103]
* __Brand__ : Hesburger                            
* __Category__ : fast_food                           
* __Opening rule__ : shops open with adapted opening hours: only take-away                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Hesburger             
* __Opening hours__ : https://www.hesburger.fi/ravintolat                    
* __Source__ : https://www.hesburger.fi/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
