### ISSUE TITLE
FI: Kotipizza

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#104]
* __Brand__ : Kotipizza                            
* __Category__ : restaurant                           
* __Opening rule__ : shops open with adapted opening hours: only take-away or by delivery                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Kotipizza             
* __Opening hours__ : https://www.kotipizza.fi/ravintolat                    
* __Source__ : https://www.kotipizza.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
