### ISSUE TITLE
FI: Tokmanni

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#105]
* __Brand__ : Tokmanni                            
* __Category__ : discount_store                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Tokmanni             
* __Opening hours__ : https://www.tokmanni.fi/stores                    
* __Source__ : https://www.tokmanni.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
