### ISSUE TITLE
FI: McDonald's

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#106]
* __Brand__ : McDonald's                            
* __Category__ : fast_food                           
* __Opening rule__ : shops open with adapted opening hours: only take-away or by delivery                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/McDonald%E2%80%99s             
* __Opening hours__ : https://www.mcdonalds.com/fi/fi-fi/palvelut/ravintolahaku.html                    
* __Source__ : https://www.mcdonalds.com/fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
