### ISSUE TITLE
FI: Sale

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#107]
* __Brand__ : Sale                             
* __Category__ :  Supermarket                          
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Sale              
* __Opening hours__ : https://www.foodie.fi/store                    
* __Source__ : https://www.foodie.fi/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
