### ISSUE TITLE
FI: K-Supermarket

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#108]
* __Brand__ : K-Supermarket                            
* __Category__ : Supermarket        
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/K-Supermarket             
* __Opening hours__ : https://www.k-ruoka.fi/k-supermarket?kauppahaku=K-Supermarket&kaikki-kaupat                 
* __Source__ : https://www.k-ruoka.fi/k-supermarket

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
