### ISSUE TITLE
FI: Osuuspankki

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#109]
* __Brand__ : Osuuspankki                            
* __Category__ : bank                           
* __Opening rule__ : shops open with adapted opening hours                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/OP_(finanssiryhm%C3%A4)             
* __Opening hours__ : https://www.op.fi/henkiloasiakkaat/asiakaspalvelu/konttorit                    
* __Source__ : https://www.op.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
