### ISSUE TITLE
FI: Subway

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#110]
* __Brand__ : Subway                            
* __Category__ : fast_food                           
* __Opening rule__ : shops open with adapted opening hours: only take-away                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Subway             
* __Opening hours__ : http://www.subway.fi/fi/ravintolat                    
* __Source__ : http://www.subway.fi/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
