### ISSUE TITLE
FI: SEO

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#111]
* __Brand__ :  SEO                           
* __Category__ : fuel                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Suomalainen_Energiaosuuskunta             
* __Opening hours__ : https://seo.fi/asemat/                    
* __Source__ : https://seo.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
