### ISSUE TITLE
FI: restaurants

### ISSUE THREAD

**Issue by posikifi** [PanierAvide/Covid_enseignes#112]
* __Country and area__ :          FI
* __Category__ :                       amenity=bar|restaurant|cafe|fast_food|pub|ice_cream
* __Legal opening rule__ :        can legally open only for delivery/takeaway
* __Time period__ :                   3.4.2020 24:00 - 31.5.2020
* __Source__ :                          https://valtioneuvosto.fi/tietoa-koronaviruksesta

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
