### ISSUE TITLE
FI: museums

### ISSUE THREAD

**Issue by posikifi** [PanierAvide/Covid_enseignes#113]
* __Country and area__ :          FI
* __Category__ :                       amenity=museums|gallery
* __Legal opening rule__ :        closed, if public operator.Recommend to be closed, if private operator
* __Time period__ :                   16.3.2020 -
* __Source__ :                          https://valtioneuvosto.fi/tietoa-koronaviruksesta

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
