### ISSUE TITLE
FI: theatre

### ISSUE THREAD

**Issue by posikifi** [PanierAvide/Covid_enseignes#114]
* __Country and area__ :          FI
* __Category__ :                       amenity=theatre|arts_centre
* __Legal opening rule__ :        closed, if public operator. Recommend to be closed, if private operator
* __Time period__ :                   16.3.2020 -
* __Source__ :                          https://valtioneuvosto.fi/tietoa-koronaviruksesta

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
