### ISSUE TITLE
FI - libraries

### ISSUE THREAD

**Issue by posikifi** [PanierAvide/Covid_enseignes#115]
* __Country and area__ :          FI
* __Category__ :                       amenity=library|mobile_library
* __Legal opening rule__ :        closed, if public operator
* __Time period__ :                   16.3.2020 -
* __Source__ :                          https://valtioneuvosto.fi/tietoa-koronaviruksesta

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
