### ISSUE TITLE
FI: Burger King

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#117]
* __Brand__ : Burger King                            
* __Category__ : fast_food                           
* __Opening rule__ : shops closed / only take-away                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Burger_King             
* __Opening hours__ : http://www.burgerking.fi/bk-restaurant                    
* __Source__ : http://www.burgerking.fi/bk-restaurant

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
