### ISSUE TITLE
FI: JYSK

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#118]
* __Brand__ : JYSK                            
* __Category__ : furniture                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Jysk              
* __Opening hours__ : https://jysk.fi/myymalat                    
* __Source__ : https://jysk.fi/tietoa-koronaviruksesta

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
