### ISSUE TITLE
FI: Instrumentarium

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#119]
* __Brand__ : Instrumentarium                             
* __Category__ : optician                           
* __Opening rule__ : shops open with adapted opening hours: opening hours depend on the shop, some are closed                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Instrumentarium             
* __Opening hours__ : https://www.instru.fi/palvelemme-teita-seuraavanlaisesti                    
* __Source__ : https://www.instru.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
