### ISSUE TITLE
FI: Silmäasema

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#120]
* __Brand__ : Silmäasema                            
* __Category__ : optician                           
* __Opening rule__ : shops open with adapted opening hours                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Silm%C3%A4asema             
* __Opening hours__ : https://www.silmaasema.fi/toimipaikat                    
* __Source__ : https://www.silmaasema.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
