### ISSUE TITLE
FI: Shell

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#121]
* __Brand__ : Shell                            
* __Category__ : fuel                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Royal_Dutch_Shell             
* __Opening hours__ : https://www.shell.fi/motorists/huoltoasemahaku.html                    
* __Source__ : https://www.shell.fi/media.html

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
