### ISSUE TITLE
FI: Nordea

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#122]
* __Brand__ : Nordea                            
* __Category__ : bank                           
* __Opening rule__ : shops open with adapted opening hours: on appoitment only                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Nordea              
* __Opening hours__ : https://www.nordea.fi/Images/146-356993/Konttoreiden_palvelutilanne.pdf                    
* __Source__ : https://www.nordea.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
