### ISSUE TITLE
FI: K-Citymarket

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#123]
* __Brand__ : K-Citymarket                             
* __Category__ : Supermarket                           
* __Opening rule__ : shops open as usual            
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/K-Citymarket            
* __Opening hours__ : https://www.k-ruoka.fi/k-citymarket?kauppahaku=K-Citymarket&kaikki-kaupat                    
* __Source__ : https://www.k-ruoka.fi/k-citymarket

**Comment by PanierAvide** [comment]
Integrated, thanks
