### ISSUE TITLE
FI: Neste

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#124]
* __Brand__ : Neste                           
* __Category__ : fuel                            
* __Opening rule__ : shops open as usual       
* __Wikipedia / Wikidata__ : https://en.wikipedia.org/wiki/Neste            
* __Opening hours__ : https://www.neste.fi/asemat                   
* __Source__ : https://www.neste.com/fi/tiedotteet-ja-uutiset/transportation/nesteen-liikenneasemat-ja-neste-k-asemat-palvelevat-tiellaliikkujia-poikkeusoloista-huolimatta

**Comment by PanierAvide** [comment]
Was already existing, I updated the opening hours URL. Thanks

**Comment by lehtojaa** [comment]
Oops. Yes it seems I had a duplicate in my list. But thanks for updating!
