### ISSUE TITLE
FI: Musti ja Mirri 

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#125]
* __Brand__ : Musti ja Mirri                        
* __Category__ : pet                         
* __Opening rule__ : shops open as usual
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Musti_ja_Mirri           
* __Opening hours__ : https://www.mustijamirri.fi/info/myymalat/                 
* __Source__ : https://www.mustijamirri.fi/mustijamirri-tiedottaa/musti-ja-mirri-tiedottaa-koronavirus

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
