### ISSUE TITLE
FI: H&M

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#126]
* __Brand__ : H&M                         
* __Category__ : clothes                        
* __Opening rule__ :   shops open as usual 
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/H%26M            
* __Opening hours__ : https://www2.hm.com/fi_fi/customer-service/shopping-at-hm/store-locator.html                  
* __Source__ : https://www2.hm.com/fi_fi/index.html

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
