### ISSUE TITLE
FI: Suomalainen kirjakauppa

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#127]
* __Brand__ : Suomalainen kirjakauppa                   
* __Category__ : books                        
* __Opening rule__ :                      shops open with adapted opening hours 
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Suomalainen_Kirjakauppa             
* __Opening hours__ : https://www.suomalainen.com/pages/myymalat
* __Source__ : https://www.suomalainen.com/blogs/ajankohtaisia-tapahtumia-ja-tuotteita/ajankohtaista-tietoa-asioinnista-ja-tilauksista

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
