### ISSUE TITLE
FI: Gasum

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#128]
* __Brand__ : Gasum                            
* __Category__ : gas                           
* __Opening rule__ : shops open as usual                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Gasum             
* __Opening hours__ : https://www.ngva.eu/stations-map/                     
* __Source__ : https://www.gasum.com/gasum-yrityksena/medialle/uutiset/2020/tietoa-liittyen-koronavirusepidemiaan-covid-19/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
