### ISSUE TITLE
FI: Otto

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#129]
* __Brand__ : Otto                             
* __Category__ : ATM                           
* __Opening rule__ : open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Ottopiste              
* __Opening hours__ : https://otto.fi/missa-otto/                    
* __Source__ : https://otto.fi/korona-saattaa-vaikuttaa-palvelutasoomme/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
