### ISSUE TITLE
FI: Toyota

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#130]
* __Brand__ : Toyota                             
* __Category__ : car                           
* __Opening rule__ : shops open as usual                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Toyota             
* __Opening hours__ :                     
* __Source__ : https://www.toyota.fi/ajankohtaista/uutiset/ajankohtaista-koronasta.json

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
