### ISSUE TITLE
FI: K-Rauta

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#132]
* __Brand__ : K-Rauta                            
* __Category__ : doityourself                        
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/K-Rauta            
* __Opening hours__ :   https://www.k-rauta.fi/myymalat                  
* __Source__ :   https://www.k-rauta.fi/palvelut/k-rauta-toimii-koronaviruksen-leviamisen-estamiseksi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
