### ISSUE TITLE
FI: Clas Ohlson

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#133]
* __Brand__ :  Clas Ohlson                           
* __Category__ : doityourself                           
* __Opening rule__ : shops open with adapted opening hours                    
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/Clas_Ohlson            
* __Opening hours__ : https://www.clasohlson.com/fi/store-finder                    
* __Source__ :   https://www.clasohlson.com/fi/covid19

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
