### ISSUE TITLE
FI: Specsavers

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#134]
* __Brand__ : Specsavers                             
* __Category__ : optician                           
* __Opening rule__ :  shops open as usual                    
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/Specsavers            
* __Opening hours__ :  https://www.specsavers.fi/liikehaku/kaikki-liikkeemme                   
* __Source__ :  https://www.specsavers.fi/covid-19/informaatio

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
