### ISSUE TITLE
FI: HalpaHalli

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#135]
* __Brand__ : HalpaHalli                            
* __Category__ : discount_store                           
* __Opening rule__ : shops open with adapted opening hours: HH Keittiö is closed                     
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/HalpaHalli            
* __Opening hours__ : https://www.halpahalli.fi/myymalat                    
* __Source__ :  https://www.halpahalli.fi/tiedotteet/halpahalli-varautuu-koronaviruksen-vaikutuksiin

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
