### ISSUE TITLE
FI: Cubus

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#136]
* __Brand__ : Cubus                            
* __Category__ : clothes                           
* __Opening rule__ : shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Cubus             
* __Opening hours__ :    https://cubus.com/fi/Corporate/Stores/
                 
* __Source__ :       https://cubus.com/fi/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
