### ISSUE TITLE
FI: KappAhl

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#137]
* __Brand__ : KappAhl                            
* __Category__ : clothes                           
* __Opening rule__ : shops open with adapted opening hours                     
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/KappAhl            
* __Opening hours__ :  https://www.kappahl.com/fi-FI/asiakaspalvelu/asiakaspalvelu/loytyyko-tuote-myymalasta/                   
* __Source__ :  https://www.kappahl.com/fi-FI/tietoa-covid-19-viruksesta/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
