### ISSUE TITLE
FI: Dressmann

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#138]
* __Brand__ :  Dressmann                           
* __Category__ : clothes                           
* __Opening rule__ : shops open with adapted opening hours                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Dressmann             
* __Opening hours__ : https://dressmann.com/fi/yrityssivut/Etsi-myymala/                    
* __Source__ :  https://dressmann.com/fi/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
