### ISSUE TITLE
FI: Espresso House

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#139]
* __Brand__ : Espresso House                            
* __Category__ : cafe                           
* __Opening rule__ : shops open with adapted opening hours: only take-away or shops closed                      
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/Espresso_House            
* __Opening hours__ :    https://fi.espressohouse.com/coffee-shops/                 
* __Source__ : https://fi.espressohouse.com/uutisia/tyontekijoidemme-ja-vieraidemme-hyvinvointi-on-meille-tarkeinta-%e2%9d%a4/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
