### ISSUE TITLE
CD: restaurants

### ISSUE THREAD

**Issue by clairedelune** [PanierAvide/Covid_enseignes#149]
* __Country and area__ :                  CD
* __Category__ :                          amenity=restaurant|cafe|fast_food|pub|ice_cream
* __Legal opening rule__ :                can legally open only for delivery/takeaway
* __Time period__ :                       19.03.2020 - 24.04.2020
* __Source__ :                            https://www.facebook.com/107142550625947/posts/209937837013084/?d=n

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
