### ISSUE TITLE
CD: bars

### ISSUE THREAD

**Issue by clairedelune** [PanierAvide/Covid_enseignes#150]
* __Country and area__ :                  CD
* __Category__ :                          amenity=bar|pub|biergarten|nightclub
* __Legal opening rule__ :                legally closed
* __Time period__ :                       19.03.2020 - 24.04.2020
* __Source__ :                            https://www.facebook.com/107142550625947/posts/209937837013084/?d=n

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
