### ISSUE TITLE
FI: Picnic

### ISSUE THREAD

**Issue by SanttuVP** [PanierAvide/Covid_enseignes#151]
* __Brand__ :                             Picnic
* __Category__ :                          Cafe
* __Opening rule__ :                      shops open with adapted opening hours
* __Wikipedia / Wikidata__ :              https://fi.wikipedia.org/wiki/Picnic_(ketju)
* __Opening hours__ :                     https://www.picnic.fi/lahin-picnic
* __Source__ :                            https://www.picnic.fi/lahin-picnic

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
