### ISSUE TITLE
CD: Shops

### ISSUE THREAD

**Issue by clairedelune** [PanierAvide/Covid_enseignes#153]
* __Country and area__ :                 CD admin7_Gombe
* __Category__ :                          shop=computer|mobile_phone|clothes
* __Legal opening rule__ :                legally closed
* __Time period__ :                       06.04.2020 - 10.05.2020
* __Source__ :                            https://information.tv5monde.com/afrique/virus-en-rdc-kinshasa-la-gombe-isoleee-les-vendeurs-de-rue-desoles-357416

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
