### ISSUE TITLE
CD: Pharmacies

### ISSUE THREAD

**Issue by clairedelune** [PanierAvide/Covid_enseignes#154]
* __Country and area__ :                 CD
* __Category__ :                          amenity=pharmacy
* __Legal opening rule__ :                legally open
* __Time period__ :                       06.04.2020 -
* __Source__ :                            https://information.tv5monde.com/afrique/virus-en-rdc-kinshasa-la-gombe-isoleee-les-vendeurs-de-rue-desoles-357416

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
