### ISSUE TITLE
CD: Food shops

### ISSUE THREAD

**Issue by clairedelune** [PanierAvide/Covid_enseignes#155]
* __Country and area__ :                 CD
* __Category__ :                          shop=supermarket|convenience|bakery|butcher
* __Legal opening rule__ :                legally open
* __Time period__ :                       25.04.2020 - 
* __Source__ :                            https://information.tv5monde.com/afrique/virus-en-rdc-kinshasa-la-gombe-isoleee-les-vendeurs-de-rue-desoles-357416

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
