### ISSUE TITLE
Brico dépot : màj

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#157]
Magasins concernés : Brico Dépôt
    Règle d'ouverture : récupération de commandes, sans contact, cours des matériaux : tous les magasins sauf Nanterre, la plupart des magasins ouverts, peu avec livraison, horaires adaptés : lundi-samedi, 8:00-15:00 - 
    Wikipédia/Wikidata : Q2889702
    Horaires : https://www.bricodepot.fr/catalogue/infos-depots-coronavirus/
    Source : https://www.bricodepot.fr/catalogue/infos-depots-coronavirus/

**Comment by PanierAvide** [comment]
Intégré, merci :+1:

**Comment by Bibi56** [comment]
Et effectivement cette page est bien mise à jour en fonction des horaires d'ouverture des magasins.
