### ISSUE TITLE
Leroy Merlin : màj

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#158]
Magasins concernés : Leroy Merlin
    Règle d'ouverture : horaires changés, magasins accessibles progressivement, retrait ou livraison des produits de première nécessité, cour accessible sur RdV
    Wikipédia/Wikidata : Q889624
    Horaires : lundi au samedi de 10h à 17h (au moins magasin de Lorient, sans doute national)
    Source : https://www.leroymerlin.fr/services/nos-services-en-magasin-pendant-confinement/vos-magasins-rouvrent-progressivement-en-libre-service.html
    Et pour les cours des matériaux : https://www.leroymerlin.fr/services/nos-services-en-magasin-pendant-confinement/votre-magasin-rouvre-cour-des-materiaux-sur-rendez-vous.html

**Comment by PanierAvide** [comment]
Intégré, merci :+1:
