### ISSUE TITLE
Pôle Emploi

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#162]
* __Brand__ :                              Pôle Emploi
* __Category__ :                         office=employment_agency
* __Opening rule__ :                   fermé jusqu'au 17, sur RdV ensuite sauf urgence (paye)
* __Wikipedia / Wikidata__ :        Q8901192
* __Opening hours__ :                week 20 off;week 21-19 open "sur rendez-vous sauf urgence
* __Source__ :                            https://www.pole-emploi.fr/actualites/information-covid-19.html

**Comment by PanierAvide** [comment]
Mis à jour via 3353750
