### ISSUE TITLE
FNAC

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#163]
* __Brand__ :                             FNAC
* __Category__ :                        shop=books
* __Opening rule__ :                  ouvert à compter de lundi 11 mai 2020
* __Wikipedia / Wikidata__ :       Q676585
* __Opening hours__ :               désolé, je n'ai que l'horaire d'un magasin et pour lundi uniquement ^^ Après je ne sais si c'est horaires normaux ou pas. En regardant la page spécifique : en regardant la page spécifique je vois ouverture une heure plus tard lundi et mardi, ensuite horaires normaux. Ça pourrait être similaire ailleurs.
* __Source__ :                            https://www.fnac.com/questions

**Comment by PanierAvide** [comment]
Mis à jour via 3353750
