### ISSUE TITLE
Brico Dépôt

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#17]
* __Magasins concernés__ :                    Brico Dépôt
* __Règle d'ouverture__ :                        magasins fermés
* __Wikipédia/Wikidata__ :                      https://www.wikidata.org/wiki/Q2889702
* __Horaires__ :                                       
* __Source__ :                                         https://www.bricodepot.fr/

**Comment by PanierAvide** [comment]
Bonjour, merci pour cette contribution ;-)
