### ISSUE TITLE
SFR

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#174]
* __Brand__ :                             SFR
* __Category__ :                        shop=mobile_phone
* __Opening rule__ :                  same ? Port du masque obligatoire
* __Wikipedia / Wikidata__ :       Q218765
* __Opening hours__ :               https://boutique.sfr.fr/ sélectionner la boutique !
* __Source__ :                            https://boutique.sfr.fr/

**Comment by PanierAvide** [comment]
Ajouté
