### ISSUE TITLE
Leroy-Merlin

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#18]
* __Magasins concernés__ :                    Leroy-Merlin
* __Règle d'ouverture__ :                        magasins fermés
* __Wikipédia/Wikidata__ :                      https://www.wikidata.org/wiki/Q889624
* __Horaires__ :                                       
* __Source__ :                                         https://www.leroymerlin.fr/

**Comment by PanierAvide** [comment]
Bonjour, merci pour cette contribution ;-)
