### ISSUE TITLE
CO:Carulla

### ISSUE THREAD

**Issue by angoca** [PanierAvide/Covid_enseignes#182]
* __Brand__ :                             Carulla
* __Category__ :                            Supermarket,
* __Opening rule__ :                      shops open with adapted opening hours: Hours are restricted by goverment in Colombia

* __Wikipedia / Wikidata__ :              https://es.wikipedia.org/wiki/Carulla / https://www.wikidata.org/wiki/Q5047480
* __Opening hours__ :                     https://www.carulla.com/almacenes
* __Source__ :                            https://www.carulla.com/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
