### ISSUE TITLE
CO:Jumbo

### ISSUE THREAD

**Issue by angoca** [PanierAvide/Covid_enseignes#183]
* __Brand__ :                             Tiendas jumbo
* __Category__ :                            Supermarket
* __Opening rule__ :                      shops open with adapted opening hours: hours are restricted by goverment
* __Wikipedia / Wikidata__ :              https://es.wikipedia.org/wiki/Jumbo_(supermercado) / https://www.wikidata.org/wiki/Q6310864
* __Opening hours__ :                     https://www.tiendasjumbo.co/institucional/nuestras-tiendas
* __Source__ :                            https://www.tiendasjumbo.co/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
