### ISSUE TITLE
CO:Olímpica

### ISSUE THREAD

**Issue by angoca** [PanierAvide/Covid_enseignes#184]
* __Brand__ :                             Olímpica
* __Category__ :                            Supermarket
* __Opening rule__ :                      shops open with adapted opening hours : Opening restricted by gouverment
* __Wikipedia / Wikidata__ :              https://es.wikipedia.org/wiki/Grupo_Empresarial_Ol%C3%ADmpica / https://www.wikidata.org/wiki/Q24749847
* __Opening hours__ :                     https://www.olimpica.com/nuestras-tiendas
* __Source__ :                            https://www.olimpica.com/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
