### ISSUE TITLE
CO:Éxito

### ISSUE THREAD

**Issue by angoca** [PanierAvide/Covid_enseignes#185]
* __Brand__ :                             Éxito
* __Category__ :                            Supermarket
* __Opening rule__ :                      shops open with adapted opening hours : Restricted by goverment
* __Wikipedia / Wikidata__ :              https://es.wikipedia.org/wiki/%C3%89xito_(supermercado) / https://www.wikidata.org/wiki/Q861947
* __Opening hours__ :                     https://www.exito.com/almacenes-exito
* __Source__ :                            https://www.exito.com/

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
