### ISSUE TITLE
Queguiner Matériaux

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#19]
* __Magasins concernés__ :                    Queguiner Matériaux
* __Règle d'ouverture__ :                        magasins fermés
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                     
* __Source__ :                                         https://www.groupe-queguiner.fr/actualites/information-covid-19/

**Comment by PanierAvide** [comment]
Bonjour, merci pour cette contribution ;-)
