### ISSUE TITLE
Crédit Coopératif

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#190]
* __Brand__ : Crédit Coopératif
* __Category__ : bank 
* __Opening rule__ :                      Mo-Fr 08:45-12:10,
Mo-Fr 13:50-7:00 (on appointment)

* __Wikipedia / Wikidata__ :              Q3006190
* __Opening hours__ :                     -
* __Source__ :  See below
Chère Cliente, Cher Client, Cher Sociétaire,

 

Nous sommes heureux de vous accueillir à nouveau le matin aux horaires habituels à partir du 15 juillet :

-    le matin nos centres d'affaires seront ouverts de 8h45 à 12h10,

-    l'après-midi exclusivement sur rendez-vous de 13h50 à 17h00

Pour respecter les consignes sanitaires et les règles de distanciation, seules 2 personnes pourront entrer dans le hall d'accueil en même temps.

Lors de votre venue en agence, il est obligatoire de vous munir d'un masque et d'un stylo.

Nous vous recommandons de privilégier les contacts à distance (mail, MSI ou par téléphone) et l'utilisation de votre banque en ligne ou votre application mobile, compte tenu de la situation.

Toutes les équipes du Crédit Coopératif restent mobilisées à vos côtés.

Nous vous remercions de votre confiance et votre compréhension.

En vous souhaitant un très bel été.

Bien cordialement,

Le Crédit Coopératif

**Comment by vinber** [comment]
je ferme car daté aout, à reprendre donc
