### ISSUE TITLE
Mise à jour de rules.csv / Update of rules.csv

### ISSUE THREAD

**Issue by vinber** [PanierAvide/Covid_enseignes#195]
**English below**

le fichier rules.csv permet de définir le statut de "brand" dans leur ensemble.
Des enseignes ne sont plus fermés car elles proposent des services de ventes à emporter ou de livraison.

donc
-  une enseigne qui ne reçoit que sur rendez vous : open_adapted et dans description "Sur rendez vous"
- une enseigne qui ne reçoit plus de publics mais livre et fait à emporter : open_adapted  et dans osm_aditionnal_tags { "takeaway:covid19": "yes","delivery:covid19": "no","access:covid19": "no" }

**EN**
the rules.csv file allows you to define the status of "brand" as a whole.
Brands are no longer closed because they offer take-away or delivery services.

so
- a "brand" which only receives by appointment: open_adapted and in description "By appointment".
- a sign that no longer receives audiences but delivers and makes to go: open_adapted and in osm_aditionnal_tags {"takeaway:covid19": "yes", "delivery:covid19": "no", "access:covid19": "no" }.

Translated with www.DeepL.com/Translator (free version)

**Comment by vinber** [comment]
- [x] alcohol
- [x] bakery
- [x] bank
- [x] beauty
- [x] cafe
- [x] car_rental
- [x] car_repair
- [x] chocolate
- [x] clothes
- [x] computer
- [x] doityourself
- [x] electronics
- [x] electronics_repair
- [x] employment_agency
- [x] farm
- [x] fast_food
- [x] flower
- [x] frozen_food
- [x] fuel
- [x] funeral_directors
- [x] furniture
- [x] garden_centre
- [x] hairdresser
- [x] hearing_aids
- [x] hotel
- [x] insurance
- [x] laundry
- [x] library
- [x] mobile_phone
- [x] optician
- [x] pet
- [x] pharmacy
- [x] post_office
- [x] restaurant
- [x] shoes
- [x] sports
- [x] stationery
- [x] supermarket
- [x] variety_store

**Comment by vinber** [comment]
cela avance, cela avance :)

**Comment by vinber** [comment]
supermarket, j'ai surtout mis en open, aucune raison que cela soit fermé et netoyé des vieux sites de références

**Comment by nlehuby** [comment]
> supermarket, j'ai surtout mis en open, aucune raison que cela soit fermé et netoyé des vieux sites de références

Oui, mais ça peut valoir le coup pour certains d'ajouter une description signalant que seuls les rayons essentiels sont ouverts

**Comment by vinber** [comment]
c'est vrai, il y a une seconde passe à faire aussi sur du click and collect dans description peut être ?
