### ISSUE TITLE
Leclerc

### ISSUE THREAD

**Issue by Camilleh9** [PanierAvide/Covid_enseignes#2]
* __Magasins concernés__ : Leclerc
* __Règle d'ouverture__ : magasins et drives ouverts
* __Wikipédia/Wikidata__ : https://fr.wikipedia.org/wiki/E.Leclerc
* __Horaires__ : (pas de changement ?)
* __Source__ : https://www.e-leclerc.com/catalogue/evenements/covid-19-les-centres-eleclerc-sont-mobilises

**Comment by PanierAvide** [comment]
Intégré, merci ;-)
