### ISSUE TITLE
Au fournil de Ben et Manon

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#21]
bakery

* __Magasins concernés__ :                    Au fournil de Ben et Manon
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales
Châteauneuf-sur-Charente : Du lundi au samedi de 6h00 à 19h30 > Mo-Sa 6:00-19:30
Roullet St Estephe : Du mardi au samedi de 7h30 à 13h30 puis de 15h30 à 18h30 > Tu-Sa 7:30-13:30, 15:30-18:30
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        https://www.facebook.com/benetmanon/
* __Source__ :                                           https://www.facebook.com/benetmanon/

**Comment by MatthieuOSM** [comment]
Ticket clos, en fait il faut une dizaine d'établissements pour référencer une enseigne (celle-ci en compte deux).

**Comment by PanierAvide** [comment]
Bonjour,

Merci pour ce ticket. L'information de commerces indépendants (moins de 10 enseignes dans une franchise) est plutôt à indiquer pour l'instant dans OpenStreetMap directement. On peut imaginer utiliser le tag `opening_hours:covid19` de cette manière :

* Fermé pendant la période : `opening_hours:covid19=off`
* Ouvert à des horaires spécifiques : `opening_hours:covid19=Mo-Sa 08:00-17:00` ([formalisme habituel](https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours))
* Ouvert aux horaires habituels : `opening_hours:covid19=Mo-Sa 08:00-20:00` (copie du tag `opening_hours`)

Cordialement.
