### ISSUE TITLE
Mutuelle de Poitiers Assurances

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#22]
insurance

* __Magasins concernés__ :                    Mutuelle de Poitiers Assurances
* __Règle d'ouverture__ :                        ouvert aux horaires habituels (privilégier la communication par mail avec votre agence)
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        https://agence.assurance-mutuelle-poitiers.fr/
* __Source__ :                                           https://www.assurance-mutuelle-poitiers.fr/covid-19-nous-restons-mobilises

**Comment by PanierAvide** [comment]
Intégré, merci :-)
