### ISSUE TITLE
Gamm Vert

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#23]
doityourself

* __Magasins concernés__ :                    Gamm Vert
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (ouverture des points de vente restreinte aux rayons alimentation et animalerie, les jours d'ouverture peuvent être modifiées et il est conseillé de contacter son magasin avant de s'y rendre)
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/Gamm_Vert
* __Horaires__ :                                        https://magasin.gammvert.fr/
* __Source__ :                                           https://www.gammvert.fr/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
