### ISSUE TITLE
Biocoop Les 7 Épis

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#24]
En fait :
supermarket | Biocoop | Q2904039 | ouvert
-- | -- | -- | --

est partiellement inexact. Par exemple ceux de l'agglo de Lorient adaptent leurs horaires.
N. B. : horaires est masculin, cf ci-dessous ;-).

* __Magasins concernés__ :                    Biocoop Les 7 Épis
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciaux (fermeture à 18 h)
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                      https://www.les7epis.fr/index.php?page=newsolo&id=305
* __Source__ :                                         https://www.les7epis.fr/index.php?page=newsolo&id=305

**Comment by PanierAvide** [comment]
Bonjour, merci du retour, c'est intégré dans le document.
