### ISSUE TITLE
CERFRANCE Poitou-Charentes

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#25]
* __Magasins concernés__ :                    CERFRANCE Poitou-Charentes
* __Règle d'ouverture__ :                        magasins ouverts aux horaires habituels (agences fermées mais interlocuteurs joignables par courriel et mobile)
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/CERFRANCE
* __Horaires__ :                                        
* __Source__ :                                           https://twitter.com/cerfrancePCH/status/1239858727299284992?s=20

**Comment by MatthieuOSM** [comment]
Au temps pour moi, cette catégorie n'est pas concernée... Corrigé !

**Comment by PanierAvide** [comment]
Effectivement je me posais la question, mais oui on cible plutôt les catégories d'enseignes potentiellement ouvertes en cette période ;-)
