### ISSUE TITLE
MACIF

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#26]
insurance

* __Magasins concernés__ :                    MACIF
* __Règle d'ouverture__ :                        agences fermées (la ligne téléphonique est fermée et sera redéployée dès que possible, il est toujours possible d'écrire et de faire ses démarches via l'espace client)
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/Mutuelle_assurance_des_commer%C3%A7ants_et_industriels_de_France_et_des_cadres_et_des_salari%C3%A9s_de_l%27industrie_et_du_commerce
* __Horaires__ :                                        
* __Source__ :                                           https://www.macif.fr/

**Comment by PanierAvide** [comment]
Merci ;-)
