### ISSUE TITLE
La Vie Claire

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#27]
supermarket

* __Magasins concernés__ :                    La Vie Claire
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (fermés le dimanche, possibles modifications d'horaires au cas par cas)
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/La_Vie_Claire
* __Horaires__ :                                        https://magasins.lavieclaire.com/lavieclaire/fr
* __Source__ :                                           https://www.lavieclaire.com/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
