### ISSUE TITLE
Naturalia

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#28]
supermarket

* __Magasins concernés__ :                    Naturalia
* __Règle d'ouverture__ :                        magasins ouverts aux horaires habituels
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/Naturalia
* __Horaires__ :                                        https://naturalia.fr/magasins/trouvez-votre-magasin-naturalia
* __Source__ :                                           https://naturalia.fr/naturalia-covid19

**Comment by PanierAvide** [comment]
Intégré, merci :-)
