### ISSUE TITLE
Intermarché

### ISSUE THREAD

**Issue by Camilleh9** [PanierAvide/Covid_enseignes#3]
* __Magasins concernés__ : Intermarché
* __Règle d'ouverture__ : magasins ouverts, horaires spécifiques pour les 70 ans et plus. 
* __Wikipédia/Wikidata__ : https://fr.wikipedia.org/wiki/Intermarch%C3%A9
* __Horaires__ : adaptées
* __Source__ : https://www.intermarche.com/enseigne/magazine/mesures-COVID

**Comment by PanierAvide** [comment]
Intégré, merci ;-)
