### ISSUE TITLE
Le Marché de Léopold

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#30]
supermarket

* __Magasins concernés__ :                    Le Marché de Léopold
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (magasins fermés entre 13h et 14h pour permettre aux équipes de travailler)
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        Mo-Sa 9:30-13:00, 14:00-18:00 https://www.lemarchedeleopold.com/magasins-bio/
* __Source__ :                                           https://www.lemarchedeleopold.com/mesurescovid19/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
