### ISSUE TITLE
Satoriz

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#31]
supermarket

* __Magasins concernés__ :                    Satoriz
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        Mo-Sa 10:00-17:00
* __Source__ :                                           http://www.satoriz.fr/animations/mesures-liees-au-covid-19/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
