### ISSUE TITLE
Biomonde

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#32]
supermarket

* __Magasins concernés__ :                    Biomonde
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (se référer au communiqué des magasins locaux sur les pages Facebook ou les contacter directement)
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        https://www.biomonde.fr/nos-magasins,1,58,1
* __Source__ :                                           https://www.facebook.com/biomondecooperative/posts/3180682271951752

**Comment by PanierAvide** [comment]
Intégré, merci :-)
