### ISSUE TITLE
NaturéO

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#33]
supermarket

* __Magasins concernés__ :                    NaturéO
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (ouverts 30 min plus tôt pour les personnes dites fragiles)
* __Wikipédia/Wikidata__ :                      
* __Horaires__ :                                        
* __Source__ :                                           https://www.natureo-bio.fr/magasin-bio/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
