### ISSUE TITLE
Les Nouveaux Robinson

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#34]
supermarket

* __Magasins concernés__ :                    Les Nouveaux Robinson
* __Règle d'ouverture__ :                        magasins ouverts à des horaires spéciales (la fermeture est à 16h00 pour l'ensemble des magasins)
* __Wikipédia/Wikidata__ :                      https://fr.wikipedia.org/wiki/Les_Nouveaux_Robinson
* __Horaires__ :                                        http://lesnouveauxrobinson.coop/les-magasins/
* __Source__ :                                           https://www.facebook.com/lesnouveauxrobinson/photos/a.10150247251555077/10163485466510077/?type=3

**Comment by PanierAvide** [comment]
Intégré, merci :-)
