### ISSUE TITLE
Crédit Coopératif - correctif

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#39]
Correction de l'information précédente :
https://www.credit-cooperatif.coop/COVID-19-Credit-Cooperatif-et-vous
C'est partiel.

Extrait :

Point horaires et fermetures temporaires

En cas de besoin, vos agences et centres d’affaires sont ouverts.
Cependant, pour garantir la sécurité de tous :

    les horaires d’ouverture des e-agences de Paris et de Bordeaux ont été modifiés. Nous sommes désormais à votre écoute, du lundi au vendredi, de 9h à 18h ;
    les agences, centres d’affaires et bureaux temporairement fermés sont : 
    - Brest ; 
    - Cergy ;
    - Dax ;
    - Metz ;
    - Niort ;
    - Saint-Etienne.

**Comment by PanierAvide** [comment]
Bien vu, merci pour la correction, c'est intégré ;-)
