### ISSUE TITLE
Carrefour

### ISSUE THREAD

**Issue by Camilleh9** [PanierAvide/Covid_enseignes#4]
* __Magasins concernés__ : Carrefour
* __Règle d'ouverture__ : magasins ouverts
* __Wikipédia/Wikidata__ : https://fr.wikipedia.org/wiki/Carrefour_(enseigne)
* __Horaires__ : 
* __Source__ : https://www.carrefour.fr/ (milieu de page)

**Comment by PanierAvide** [comment]
Intégré, merci ;-)
