### ISSUE TITLE
AG2R La Mondiale

### ISSUE THREAD

**Issue by Cybereric** [PanierAvide/Covid_enseignes#40]
* __Magasins concernés__ : AG2R La Mondiale  
* __Règle d'ouverture__ :    fermés   
* __Wikipédia/Wikidata__ :  Q292228      
* __Horaires__ :                                     
* __Source__ :   https://www.ag2rlamondiale.fr   
* __Infos__ :  contact en priorité par mail

**Comment by PanierAvide** [comment]
Bonjour, c'est intégré, merci :-)
