### ISSUE TITLE
CNP Assurances

### ISSUE THREAD

**Issue by Cybereric** [PanierAvide/Covid_enseignes#41]
* __Magasins concernés__ :   CNP Assurances              
* __Règle d'ouverture__ :   fermés                    
* __Wikipédia/Wikidata__ :   Q1023930                  
* __Horaires__ :                                    
* __Source__ :     https://www.cnp.fr                               
* __Infos__ :  Contacts par formulaires de contact

**Comment by PanierAvide** [comment]
Bonjour, c'est intégré, merci :-)
