### ISSUE TITLE
Office Dépôt

### ISSUE THREAD

**Issue by mlorant** [PanierAvide/Covid_enseignes#47]
* __Magasins concernés__ :  Office Dépôt
* __Règle d'ouverture__ : magasins fermés
* __Wikipédia/Wikidata__ : https://www.wikidata.org/wiki/Q1337797
* __Source__ :    https://www.officedepot.fr/, voir bandeau en-tête

**Comment by PanierAvide** [comment]
C'est intégré, merci ;-)
