### ISSUE TITLE
Optic 2000

### ISSUE THREAD

**Issue by mlorant** [PanierAvide/Covid_enseignes#48]
* __Magasins concernés__ :  Optic 2000
* __Règle d'ouverture__ :  magasins fermés
* __Wikipédia/Wikidata__ :  https://www.wikidata.org/wiki/Q3354445
* __Horaires__ :  
* __Source__ :  https://www.optic2000.com

**Comment by mlorant** [comment]
Mea culpa pour celui là, il est déjà dans le CSV mais sous le nom "Optic2000" (sans espace), je l'ai pas trouvé à ma première recherche :-)

**Comment by PanierAvide** [comment]
J'ai changé avec la version "espacée" vu que c'est plutôt ça qui ressort dans OSM, merci du signalement.
