### ISSUE TITLE
Affichage carte Outre Mer

### ISSUE THREAD

**Issue by cecilaki** [PanierAvide/Covid_enseignes#49]
Bonjour, je suis en Guyane et j'aimerais bien contribuer sur ce territoire, mais pour l'instant la carte ne s'affiche pas, j'ai un écran blanc. Je me demandais les raisons et si je pouvais y faire quelque chose. Merci. 

<img width="1129" alt="Capture d’écran 2020-03-25 à 10 27 43" src="https://user-images.githubusercontent.com/6681719/77541391-60adde80-6e83-11ea-9296-ca4ef5c69432.png">

**Comment by francois2metz** [comment]
Bonjour, j'ai tenté un correctif, vous pouvez regarder a nouveau ?

**Comment by PanierAvide** [comment]
Bonjour, les données pour la Guyane vont être intégrées très rapidement (demain ou après-demain), en attendant il est toujours possible de contribuer dans OpenStreetMap.

**Comment by cecilaki** [comment]
Oui c'est bon, merci. Pb solved. Je vais attendre alors les données pushées bientôt et je contribuerai ensuite sur cette base !

**Comment by PanierAvide** [comment]
Super, merci de votre retour et nous restons à disposition si besoin :-)

**Comment by cecilaki** [comment]
Merci, et de même, je suis à dispo ;-)
