### ISSUE TITLE
Ajout des laboratoires d'analyse ?

### ISSUE THREAD

**Issue by fbroussais** [PanierAvide/Covid_enseignes#50]
Bonjour,
Suite à un message d'un laboratoire d'analyse médical privé qui annonçait qu'ils restaient ouverts (+ aménagements spéciaux), je me suis rendu compte que leur tag n'était pas traité ici (du moins je n'ai pas trouvé si c'est le cas).
healthcare=laboratory

cf. [https://wiki.openstreetmap.org/wiki/FR:Tag:healthcare%3Dlaboratory](https://wiki.openstreetmap.org/wiki/FR:Tag:healthcare%3Dlaboratory)

Mais c'est peut-être normal ?

**Comment by PanierAvide** [comment]
Bonjour,

Merci pour ce retour. À minima les informations concernant les réseaux de laboratoires peuvent être renseignées dans ce dépôt GitHub (si vous avez des infos). Pour tout ce qui est affichage sur caresteouvert.fr, la question se pose sur les services de santé au sens large : afficher ou non, en sachant qu'il n'est pas recommandé de s'y déplacer sans raison valable. Pour l'instant nous n'avons pas encore tranché.

Cordialement.

**Comment by fbroussais** [comment]
Bonjour,
C'est ce que je me disais concernant ces services de santé.
Je n'ai les infos que sur des labos dans et autour du Grand Nancy, et lorsqu'ils sont  + de 10, il y a pas mal de spécificités.
Bonne journée.

**Comment by PanierAvide** [comment]
Bonjour, la discussion continue sur le dépôt dédié à la carte "ça reste ouvert" ici : https://github.com/osmontrouge/covid19_map/issues/12

Je ferme le ticket ici.
