### ISSUE TITLE
Banque Populaire (màj)

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#51]
Attention : ne pas modifier tant que https://github.com/osmontrouge/covid19_map/issues/37 n'est pas traîté/répondu.

Bonjour :
bank | Banque Populaire | Q846647 | ouvert |   | Privilégier les échanges à distance
-- | -- | -- | -- | -- | --

Ça c'est la pub.

bank | Banque Populaire | Q846647 | partiel|   | Privilégier les échanges à distance
-- | -- | -- | -- | -- | --

Ça c'est la réalité.

Exemple : https://www.bpgo.banquepopulaire.fr/portailinternet/Editorial/VotreBanque/Pages/Recherche-par-ville.aspx?cityTxt=56520

En fait DAB ouvert, conseillers joignables mais agence fermée.

L'agence de Quimperlé (de mémoire) reste ouverte avec notamment du personnel de Guidel.

* __Magasins concernés__ :                    Banque Populaire
* __Règle d'ouverture__ :                        
* __Wikipédia/Wikidata__ :                      Q846647 
* __Horaires__ :                                        partiel
* __Source__ :                                          survey!

**Comment by PanierAvide** [comment]
Merci du retour
