### ISSUE TITLE
Laverie Lav'Club

### ISSUE THREAD

**Issue by MicMo27** [PanierAvide/Covid_enseignes#52]
* __Magasins concernés__ : Laverie Lav'Club       
* __Règle d'ouverture__ : magasins ouverts aux horaires habituels 
* __Wikipédia/Wikidata__ :                      
* __Horaires__ : http://lavclub.net 
* __Source__ : http://lavclub.net/info-coronavirus-laverie-ouverte/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
