### ISSUE TITLE
Lapeyre

### ISSUE THREAD

**Issue by mlorant** [PanierAvide/Covid_enseignes#53]
* __Magasins concernés__ :     Lapeyre
* __Règle d'ouverture__ :    fermés
* __Wikipédia/Wikidata__ :   brand:wikidata=Q3117467
* __Horaires__ :  
* __Source__ :    https://www.facebook.com/photo/?fbid=2740481425989612&set=a.133038246733956

**Comment by PanierAvide** [comment]
Ajouté, merci :-)
