### ISSUE TITLE
Super U : mise à jour

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#57]
* __Magasins concernés__ :                    Super U
* __Règle d'ouverture__ :                        horaires adaptés
* __Wikipédia/Wikidata__ :                      inchangé
* __Horaires__ :                                      https://www.magasins-u.com/fichiers/horaires-magasins_pdf
* __Source__ :                                         https://www.magasins-u.com/fichiers/horaires-magasins_pdf

**Comment by PanierAvide** [comment]
Intégré, merci :+1:
