### ISSUE TITLE
Brico Dépôt : màj

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#59]
* __Magasins concernés__ :                    Brico Dépôt
* __Règle d'ouverture__ :                        récupération de commandes, sans contact, horaires adaptés : lundi-samedi, 8:00-15:00 - pas tous les magasins
* __Wikipédia/Wikidata__ :                      Q2889702
* __Horaires__ :                                       https://www.bricodepot.fr/lorient/brico-depot-drive/
* __Source__ :                                           https://www.bricodepot.fr/lorient/brico-depot-drive/

**Comment by PanierAvide** [comment]
Intégré, merci :-)
