### ISSUE TITLE
Leroy Merlin : màj

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#60]
* __Magasins concernés__ :                    Leroy Merlin
* __Règle d'ouverture__ :                        semble les horaires normaux, uniquement retrait ou livraison des produits de première nécessité
* __Wikipédia/Wikidata__ :                      Q889624 
* __Horaires__ :                                      lundi au samedi de 10h à 18h (au moins magasin de Lorient, sans doute national)
* __Source__ :                                        https://www.leroymerlin.fr

**Comment by PanierAvide** [comment]
À priori tous les magasins ne sont pas ouverts, j'ai ajouté l'info `partiel`. Merci du retour.

**Comment by Bibi56** [comment]
Les magasins en soit sont fermés et on ne peut pas commander tout et n'importe quoi, donc `partiel` n'est pas choquant.

**Comment by Bibi56** [comment]
Actuellement certaines/les cours de matériaux sont ouvertes sur rendez-vous :
https://www.leroymerlin.fr/services/service-client/vos-magasins-rouvrent-cour-des-materiaux-sur-rendez-vous.html

Les magasins concernés : 
    Agen
    Albi
    Aubagne 2
    Bayonne
    Besancon 2
    Biganos
    Blois
    Bois D'Arcy
    Bonneuil
    Bouliac
    Bourges
    Brive
    Cabries
    Calais3
    Charleville Mezieres
    Chateauroux
    Chelles
    Dijon
    Dreux
    Frejus
    Gonesse
    Gradignan
    Isneauville
    La Rochelle dès ven 10/04
    La Valentine
    Laval 2
    Le Mans
    Lens
    Lesquin
    Lognes
    Lorient
    Lyon Bron
    Macon Sud
    Marseille Littoral
    Martigues dès ven 10/04
    Melun 2
    Merignac
    Metz
    Metz Technopole
    Monsoult
    Montigny
    Montpellier
    Nancy
    Nancy Sud
    Nice
    Nimes
    Niort
    Orleans
    Pau
    Perigueux
    Poitiers
    Reims Cormontreuil
    Reims Nord
    St Aunes
    St etienne
    Ste Genevieve
    Toulouse Balma
    Toulouse Colomiers
    Toulouse Roques dès ven 10/04
    Tourcoing 2
    Tours Nord
    Tours Sud
    Trignac
    Valenciennes
    Vallauris
    Villeneuve
    Vourles

**Comment by PanierAvide** [comment]
Je me rends pas compte, sur le total ça concerne plus de 75% des magasins de France ?

**Comment by Bibi56** [comment]
Je pensais la quasi-totalité, en fait j'avais sans doute tort. Les exceptions sont peut-être les magasins sans cours des matériaux ! Bon il y a au moins deux exceptions : Chantepie (Rennes), Quimper. Je ne sais si les magasins parisiens ont des cours du matériaux.
La liste fait 67 éléments, En 2017, il y avait 142 Leroy-Merlin (pas Weldom qui fait partie du même groupe), donc on est plus proche de 50 %. Ce qui serait sympa c'est un niveau entre Covid_enseignes et caresteouvert où on dirait qu'on a des informations. Comme ça le contributeur peut contribuer plus facilement qu'en refaisant les mêmes recherches.

**Comment by PanierAvide** [comment]
Alors j'ai changé le fichier `rules.csv` pour intégrer les nouvelles URL avec les infos et liste des magasins ouverts. J'ai laissé le statut `partial` comme on est sur du 50-50 ouvert/fermé. Sur ça reste ouvert, l'utilisateur peut vérifier si son magasin est concerné par l'ouverture avec le lien "voir les horaires sur le site de l'enseigne". Et si on veut aller plus loin, effectivement il faut intégrer les infos au cas par cas dans OSM.

**Comment by Bibi56** [comment]
Pas mal, je trouve dommage que l'url ne soit pas visible depuis caresteouvert.
"Uniquement retrait ou livraison des produits de première nécessité" est maintenant obsolète.
"Uniquement retrait ou livraison des produits de première nécessité. Cours des matériaux éventuellement accessible sur réservation." serait plus juste.

**Comment by PanierAvide** [comment]
Le lien est bien affiché, exemple dans le panneau de droit "Horaires sur le site web de l'enseigne" renvoie au lien du fichier CSV covid_enseignes : https://www.caresteouvert.fr/@48.164320,-1.632663,17.82/place/w81983313

**Comment by Bibi56** [comment]
Subtile, comme c'est un texte "ordinaire", et que le texte est "Horaires sur le site web de l'enseigne" avec en dessous le lien générique du magasin, je n'ai pas fait attention au curseur effectivement différent. De plus le fond blanc fait aussi penser à une zone inactive.
Peut-être le classique lien bleu souligné (ça fait daté) ou un signe (une flèche →➤⇒ ou un globe 🌐?)
Sinon changer le texte en quelque chose comme "Consulter les horaires" (on verra bien que c'est le site de l'enseigne et évidemment le site web pas le magasin).

**Comment by PanierAvide** [comment]
Comme c'est un souci d'ergonomie, peux-tu ouvrir un ticket pour cette suggestion sur le dépôt du site web "ça reste ouvert" : https://github.com/osmontrouge/caresteouvert

Ça permettra de discuter de la solution qui fait un bon équilibre ergonomie/design ;-)
