### ISSUE TITLE
Queguiner Matériaux : màj

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#61]
* __Magasins concernés__ :                    Queguiner Matériaux
* __Règle d'ouverture__ :                       magasins ouverts aux horaires habituels
* __Wikipédia/Wikidata__ :                      Q3414861 
* __Horaires__ :                                      semble les horaires normaux
* __Source__ :                                         https://www.queguiner.fr/

**Comment by PanierAvide** [comment]
Sur la page https://www.groupe-queguiner.fr/actualites/information-covid-19/ c'est pas si clair que tous les magasins sont ouverts, j'ai mis en partiel. Merci du retour.

**Comment by Bibi56** [comment]
Bien vu, je n'avais pas trouvé. Outre le service réduit, le nombre de magasins "ouverts" est effectivement réduit à Landivisiau, Quimper, Vannes, Treillières, Saint-Brieuc, Rennes et Chavagne. Ils ont d'autres magasins
