### ISSUE TITLE
Drive Fermier

### ISSUE THREAD

**Issue by karawitan** [PanierAvide/Covid_enseignes#62]
* __Magasins concernés__ :   Bienvenue à la Ferme - Drive Fermier (85 magasins en France)
* __Règle d'ouverture__ :   Règles d'ouvertures sont spécifiques à chaque magasin, se reporter au site en ligne du magasin
* __Wikipédia/Wikidata__ :     https://fr.wikipedia.org/wiki/Bienvenue_%C3%A0_la_ferme
* __Horaires__ :                                        
* __Source__ :  https://www.drive-fermier.fr/carte_drive_fermier

**Comment by PanierAvide** [comment]
Merci, c'est intégré via 586ef7e
