### ISSUE TITLE
5àSec

### ISSUE THREAD

**Issue by mlorant** [PanierAvide/Covid_enseignes#63]
* __Brand__ :  5àSec
* __Opening rule__ : off
* __Wikipedia / Wikidata__ : brand:wikipedia=fr:5àsec ; brand:wikidata=Q2817899
* __Opening hours__ : 
* __Source__ :  https://www.5asec.fr/trouvez-votre-pressing

**Comment by PanierAvide** [comment]
Thanks :+1:
