### ISSUE TITLE
Brands with inconsistent naming?

### ISSUE THREAD

**Issue by caugner** [PanierAvide/Covid_enseignes#64]
While preparing chain data for Germany (https://github.com/caugner/caresteouvert-de/issues/6), I came across brands with inconsistent naming like the following:

* `nah & gut` = `Nah & Gut` = `nah und gut` = `Nah und Gut`
* `Netto Markendiscount ` = `Netto Marken Discount` = `Netto Marken-Discount`
* `Penny` = `PENNY` = `Pennnymarkt` = `Penny Markt` = `Penny-Markt` = `PENNY Markt`

I wonder:

* Do these issues also exist in France?
* Do you handle these inconsistencies somehow?
* Are the brand names matched only against `name=*` or against other OSM tags as well?

**Comment by PanierAvide** [comment]
This is handled in several steps :
* If both OSM feature and brand in CSV have Wikidata ID, no problem, matching is done using it so brand name doesn't matter
* If either OSM feature or brand in CSV lack Wikidata ID, we try matching by name : lowercase + unaccented version of both string
* Some clean-up can be done also directly in OSM, only one brand name is normally correct
* Finally, for some rare cases, entries could be duplicated in brand CSV file to handle very different names (for example in France : `Système U`, `Magasins U`, `Super U`, `Hyper U` share same Wikidata ID and are technically correct brand names).

This is done here : https://github.com/osmontrouge/caresteouvert/blob/master/db/update_poi.sql#L129 and could be improved to remove as well characters like `-` or `&`

**Comment by caugner** [comment]
Thanks for the explanation!
