### ISSUE TITLE
Société Générale - Ajout de règle en description

### ISSUE THREAD

**Issue by MatthieuOSM** [PanierAvide/Covid_enseignes#66]
Salut François !

Est-il possible d'ajouter pour Société Générale ceci en colonne description ? (je ne sais pas si ça fait trop ou pas, j'ai juste fait un copier/coller ici pour préciser les règles de la banque sur les horaires ouvertes sous contrainte)
```
Pour répondre aux urgences qui ne pourraient pas être prises en charge à distance, nos agences restent ouvertes :
– le matin, sur rendez-vous.
– l’après-midi, uniquement par téléphone.
```

Vu sur (ou pas pop-up la première fois arrivé sur le site) :
https://particuliers.societegenerale.fr/articles-actualites/covid-19

Cette règle générale complèterait les agences qui ont (au cas par cas) les infos type adresse, téléphone et horaires sur Ça reste ouvert.

**Comment by PanierAvide** [comment]
Bonjour, merci de ce retour, l'actualisation a été intégrée ;-)
