### ISSUE TITLE
magasins d'optique

### ISSUE THREAD

**Issue by Bibi56** [PanierAvide/Covid_enseignes#69]
J'ai demandé au producteur de données pour l'ajout sur CaResteOuvert. Mais un bandeau standard pourrait éviter de mettre description:covid19 en plus de opening_hours:covid19

* __Brand__ :                             tous sauf les franchisés des chaînes explicitement fermées !
* __Opening rule__ :                  shops open with adapted opening hours
* __Wikipedia / Wikidata__ :       
* __Opening hours__ :               
* __Source__ :                          sur rendez-vous et pour urgences, voir https://www.urgenceopticien.fr

**Comment by PanierAvide** [comment]
Je viens de regarder dans le 35, on est loin du cas où tous les indépendants sont ouverts vu la liste proposée sur le site. Ça me paraît plus logique de renseigner au cas par cas dans OSM. Mieux vaut avoir trop d'infos dans OSM que pas assez ?

**Comment by Bibi56** [comment]
Oui c'est une minorité, dans le 56 j'ai vu un opticien en principe non ouvert entrer dans sa boutique, peut-être juste pour relever le courrier, je ne sais s'il a ouvert après.
Mais justement comme le principe c'est d'appeler et sur rendez-vous, avoir une info disant où les trouver est utile même pour un opticien fermé.
Sinon l'utilisateur se "casse les dents"
Si possible dire par défaut qu'on ne sait si le magasin est ouvert et pour chaque magasin de la liste on l'ajoute dans caresteouvert. Ainsi le commentaire générique est prédéfini (ici défini sur le magasin lui même).

Exemple :
[Optique Stéphan, Auray](https://www.caresteouvert.fr/@47.666200,-2.983045,21.07/place/w197228005)

**Comment by PanierAvide** [comment]
Ce serait plus ça l'approche oui, ou alors le gérer dans le code de ça reste ouvert comme une règle écrite en dur spécial opticien indépendant de France. Mais on aura probablement plus vite fait des les éditer dans OSM.
