### ISSUE TITLE
US: Safeway

### ISSUE THREAD

**Issue by rjsheperd** [PanierAvide/Covid_enseignes#70]
* __Brand__ : Safeway
* __Opening rule__ : shops open with adjusted hours, "Contact Free" delivery and pickup available at all stores.
* __Wikipedia / Wikidata__ : https://www.wikidata.org/wiki/Q1508234
* __Opening hours__ :  Most are open 07:00 - 22:00 (https://local.safeway.com/search.html)
* __Source__ :  https://www.safeway.com/faq/covid-19-faq.html

**Comment by PanierAvide** [comment]
This is integrated, thank you :+1:
