### ISSUE TITLE
US: 7-Eleven

### ISSUE THREAD

**Issue by rjsheperd** [PanierAvide/Covid_enseignes#71]
* __Brand__ : 7-Eleven
* __Opening rule__ : shops open with adjusted hours 
* __Wikipedia / Wikidata__ : https://www.wikidata.org/wiki/Q259340
* __Opening hours__ :  05:00 - 24:00
* __Source__ :  (https://www.7-eleven.com/coronavirus-safety)

**Comment by PanierAvide** [comment]
This is integrated, thank you :+1:
