### ISSUE TITLE
US: Walgreens

### ISSUE THREAD

**Issue by rjsheperd** [PanierAvide/Covid_enseignes#72]
* __Brand__ : Walgress
* __Opening rule__ : shops open with adjusted hours
* __Wikipedia / Wikidata__ : https://www.wikidata.org/wiki/Q1591889
* __Opening hours__ :  09:00 - 17:00
* __Source__ :  https://news.walgreens.com/our-stories/covid-19-faq.htm

**Comment by PanierAvide** [comment]
This is integrated, thank you :+1:
