### ISSUE TITLE
US: Fred Meyer

### ISSUE THREAD

**Issue by rjsheperd** [PanierAvide/Covid_enseignes#73]
* __Brand__ : Fred Meyer
* __Opening rule__ : shops open with adjusted hours
* __Wikipedia / Wikidata__ : https://www.wikidata.org/wiki/Q5495932
* __Opening hours__ :  07:00 - 21:00, with 07:00-08:00 dedicated to Senior shoppers (https://www.fredmeyer.com/i/coronavirus-update/store-information)
* __Source__ :  https://www.fredmeyer.com/i/coronavirus-update

**Comment by PanierAvide** [comment]
This is integrated, thank you :+1:
