### ISSUE TITLE
US: Walmart

### ISSUE THREAD

**Issue by rjsheperd** [PanierAvide/Covid_enseignes#74]
* __Brand__ : Walmart
* __Opening rule__ : shops open with adjusted hours
* __Wikipedia / Wikidata__ : https://www.wikidata.org/wiki/Q483551
* __Opening hours__ :  07:00 - 20:30, with 07:00-08:00 dedicated to Senior shoppers (https://corporate.walmart.com/important-store-info)
* __Source__ :  https://corporate.walmart.com/here-for-you

**Comment by PanierAvide** [comment]
This is integrated, thank you :+1:
