### ISSUE TITLE
Split value "partial" into few|some|most

### ISSUE THREAD

**Issue by caugner** [PanierAvide/Covid_enseignes#75]
If I understand correctly, `partial`  is used both for "only few places open" and "most but not all places open".

It would be useful to be more specific, which would allow the app to show a more meaningful message:

* `few` = "This place is probably closed, as only few places of this brand are reportedly open."
* `some` = `partial` = "This place may be open, but only some places of this brand are reportedly open."
* `most` = "This place is probably opened, as most places of this brand are reportedly open."

**Comment by PanierAvide** [comment]
Thanks for this suggestion. Though it would be interesting to have such level of detail, it seems quite hard to know based on what brands show on their website.

**Comment by caugner** [comment]
Hm, when I researched for Germany, I came across a few banks that have most (but not all) of their offices open. I tagged those as "partial", even though "most" would have been more appropriate.

**Comment by PanierAvide** [comment]
If we look from user side, in all cases if it is few/some/most, user can't be sure if it is really open, and has to check in all cases before going.

**Comment by caugner** [comment]
Hm, maybe I could have simply tagged them as `open` as a better approximation of `most`. Even for brands declaring that their shops remain `open`, we cannot guarantee that they are actually open. Some individual shops could be closed.

Would be interesting to determine if there are any cases where invidiual places are tagged as closed even though the rule would suggest otherwise.

**Comment by PanierAvide** [comment]
Yes, using open or open_adapted seems a good option. I checked and 282 features are marked as closed when brand opening rule is either open or open_adapted.

**Comment by PanierAvide** [comment]
Don't hesitate to close issue if you feel this solution is OK.

**Comment by caugner** [comment]
That's okay for me, I will communicate that approach towards the German contributors.
