### ISSUE TITLE
Export brand list template from OSM?

### ISSUE THREAD

**Issue by caugner** [PanierAvide/Covid_enseignes#78]
I [already mentioned this idea](https://github.com/bleibtoffen/caresteouvert-de/issues/29#issuecomment-609944805) on Monday: Wouldn't it be possible to extract a list of `category,name,wikidata_id` directly from OSM (using individual countries' dumps), basically like this:

```sql
  SELECT o.shop AS shop_type,
         o.brand:wikidata_id AS wikidata_id,
         COUNT(*),
         GROUP_CONCAT(DISTINCT o.name) AS names
    FROM objects o
   WHERE  o.name IS NOT NULL
     AND o.shop IS NOT NULL
     AND o.brand:wikidata_id IS NOT NULL
GROUP BY o.shop,
         o.brand:wikidata_id
```

**In other words**: For objects of any type with `shop=*` and `brand:wikidata_id=*`
1. count the number of occurences and
2. return all used `name=*` values in comma-separated form (or even better: `name1=count1,name2=count2` etc).

**Comment by PanierAvide** [comment]
I proposed to François to set-up a `brands.csv` file which will contain daily statistics for brands through countries, with this format :
* Date
* Country
* Brand name
* Opening rule
* Number of POIs

That way, we can see how it evolves through time, and also see brands by country not having an opening rule defined in Covid_enseignes. I will keep you updated when this will be available (soon I hope !).

**Comment by caugner** [comment]
> I proposed to François to set-up a `brands.csv` file which will contain daily statistics

If you do this, please consider splitting the statistics per country (`DE.csv`, `FR.csv` etc.). This way, it's more likely the file can still be viewed and filtered directly in GitHub.

**Comment by PanierAvide** [comment]
List is available here : https://download.osmontrouge.fr/caresteouvert/stats_brands.csv

It will be updated daily. For now we went with a single file, which you can open in a spreadsheet software and do filtering with. If it becomes a real problem, we will split by country (needs a bit more code to do so).

**Comment by caugner** [comment]
Thanks!

Just wondering @PanierAvide:
* Could we have a column for wikidata_id (`brand:wikidata`)?
* Have you considered creating a `carestouvert-stats` repository for that and have the cronjob commit and push there? Without the `date` column, this would give a nice history I guess.

**Comment by PanierAvide** [comment]
I asked François to add wikidata ID. A repo for all stats would be helpful, we will discuss tomorrow in a phone call of having various statistics available. I'm not sure however of managing date through Git, as a data analyst I prefer to have a single CSV file which can be parsed easily and integrated in a DB or LibreOffice. It seems quite complex to go through whole Git repo history to get data with dates.
