### ISSUE TITLE
Add delivery + takeaway column

### ISSUE THREAD

**Issue by caugner** [PanierAvide/Covid_enseignes#86]
Right now, the `rules.csv` format basically allows us to specify:

* `opening_hours:covid19`
* `description:covid19`

It would be helpful to also specify:

* `delivery:covid19`
* `takeaway:covid19`

Like this, we can set those columns to `only` for eligible chains without having to specify "Delivery only" in the description.

**Comment by PanierAvide** [comment]
As discussions goes on about adding several kind of tags in a near future, I would be more confident about adding a single `tags` columns, where we could set up any complementary OSM tag, thus making it more flexible for the future. This column could be in JSON format for easy parsing and integration.

**Comment by PanierAvide** [comment]
This has been implemented, thanks !
