### ISSUE TITLE
FI: ABC

### ISSUE THREAD

**Issue by posikifi** [PanierAvide/Covid_enseignes#92]
* __Brand__ :                             ABC
* __Opening rule__ :                 shops open with adapted opening hours: depends station by station
* __Wikipedia / Wikidata__ :     https://fi.wikipedia.org/wiki/ABC-ketju
* __Opening hours__ :              https://www.abcasemat.fi/fi/uutiset/abc-asemien-ja-rahtaritilojen-poikkeusaukioloajat-kevaalla-2020
* __Source__ :                           https://www.abcasemat.fi/fi/asemat

**Comment by PanierAvide** [comment]
This is integrated, thanks for your feedback.
