### ISSUE TITLE
FI: K-Market

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#93]
* __Brand__ : K-Market                            
* __Opening rule__ : shops open as usual                 
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/K-Market
* __Opening hours__ : https://www.k-ruoka.fi/k-market?kauppahaku=K-Market&kaikki-kaupat                
* __Source__ : https://www.k-ruoka.fi/k-market

**Comment by PanierAvide** [comment]
This has been added, thanks :+1:
