### ISSUE TITLE
Renault

### ISSUE THREAD

**Issue by pyrog** [PanierAvide/Covid_enseignes#94]
At least, [w115898848](https://www.caresteouvert.fr/@46.858922,0.939394,18.33/place/w115898848) is opened

* __Brand__ :                             Renault
* __Opening rule__ :                      
* __Wikipedia / Wikidata__ :              
* __Opening hours__ :                     
* __Source__ :                            the operator of this garage  02 47 94 50 43

See https://github.com/osmontrouge/caresteouvert/issues/398

**Comment by PanierAvide** [comment]
Mis à jour, sur le site de Renault on voit qu'une partie des garages sont ouverts. Cf c7836de
