### ISSUE TITLE
FI: Lidl

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#95]
* __Brand__ : Lidl                            
* __Opening rule__ : shops open as usual                      
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/Lidl            
* __Opening hours__ : https://www.lidl.fi/myymaelaet                    
* __Source__ : https://www.lidl.fi/myymaelaet

**Comment by PanierAvide** [comment]
This has been added, thanks :+1:
