### ISSUE TITLE
FI: R-Kioski

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#96]
* __Brand__ : R-Kioski                            
* __Opening rule__ : shops open with adapted opening hours                  
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/R-kioski            
* __Opening hours__ : https://www.r-kioski.fi/kioskit/                    
* __Source__ :  https://www.r-kioski.fi/kioskit/

**Comment by PanierAvide** [comment]
This has been added, thanks :+1:
