### ISSUE TITLE
FI: Teboil

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#97]
* __Brand__ : Teboil                            
* __Opening rule__ : shops open with adapted opening hours: depends station by station                      
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/Teboil             
* __Opening hours__ : https://www.teboil.fi/yhtio/ajankohtaista/poikkeavat-aukioloajat-alkaen-18.3.2020/                    
* __Source__ : https://www.teboil.fi/

**Comment by PanierAvide** [comment]
Integrated, thanks. If you are confident with LibreOffice + GitHub, don't hesitate to offer a pull request for next feedbacks. If not, you can continue sending issues this way :wink:
