### ISSUE TITLE
FI: Neste

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#98]
* __Brand__ : Neste                     
* __Category__ : fuel                            
* __Opening rule__ : shops open as usual                  
* __Wikipedia / Wikidata__ :  https://fi.wikipedia.org/wiki/Neste-asemaketjut                
* __Opening hours__ : https://www.neste.fi/asemat                    
* __Source__ : https://www.neste.fi

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
