### ISSUE TITLE
FI: S-market

### ISSUE THREAD

**Issue by lehtojaa** [PanierAvide/Covid_enseignes#99]
* __Brand__ :  S-market                           
* __Category__ : Supermarket                           
* __Opening rule__ :  shops open as usual                     
* __Wikipedia / Wikidata__ : https://fi.wikipedia.org/wiki/S-market              
* __Opening hours__ : https://www.s-kanava.fi/web/smarkethokelanto/etusivu#myymalat                    
* __Source__ : https://www.s-kanava.fi/web/smarkethokelanto

**Comment by PanierAvide** [comment]
Integrated, thanks :+1:
